language: python
python:
    - 3.7
    - 3.5
    - 2.7
install:
  - pip install jupyter
  - pip install .
  - python -m tlaplus_kernel.install
script:
  - python setup.py test
os:
  - linux
  - windows