language: python
python:
    - "nightly"
    - "3.7-dev"
    - 3.6
    - 3.5
    - 2.7
install:
  - pip install jupyter
  - pip install .
  - python3 -m tlaplus_kernel.install
script:
  - python setup.py test

